added timestamp in order to detect any delay from any event
wazo-platform/xivo-bus pull request #38
Opened 2021-05-31 19:13 UTC by oxynor

2021-06-01 13:49 UTC, oxynor commented
recheck

2021-06-09 13:18 UTC, bloom1 requested changes
Good work :smiley:

2021-06-09 13:18 UTC, bloom1 commented on xivo_bus/tests/test_marshaler.py
> +    @patch("xivo_bus.marshaler.datetime")
Consistency: we try to use the same string quote style across the code. In this case, it should be single quotes (`'str'`)

2021-06-15 12:33 UTC, bloom1 commented
@oxynor up

2021-06-16 14:12 UTC, bloom1 approved these changes

2021-06-16 14:18 UTC, merged